### ISSUE TITLE
require-css.js

### ISSUE THREAD

**Issue by hubiao1** [Treri/angular-require#2]
给一个require-css.js下载链接吧。。。

**Comment by hubiao1** [comment]
require-css.js

**Comment by hubiao1** [comment]
require-css.js

**Comment by hubiao1** [comment]
require-css.js

**Comment by hubiao1** [comment]
顶起来

**Comment by ik0r** [comment]
https://github.com/guybedford/require-css
https://github.com/martinsb/require-css
https://github.com/tyt2y3/requirejs-css-plugin

You can google a lot

**Comment by hubiao1** [comment]
然后怎么引入 ？我也谷歌了，但结果还是不理想。。报错

**Comment by hubiao1** [comment]
@Treri

**Comment by hubiao1** [comment]
你把你的例子完整的例出来，大家直接下载 你的就好。免得东奔西找。。。伟大的作者，你说是不？

**Comment by hubiao1** [comment]
@Treri

**Comment by hubiao1** [comment]
@Treri
